### ISSUE TITLE
Updated URL to get account number

### ISSUE THREAD

**Issue by Ben-Reg** [lawrencefoley/evergy#34]
Hello @lawrencefoley ,

Evergy just did a site redesign, and the account number is no longer where it used to be.

I know you are no longer maintaining this project, but I've found a new way to get the account number and could put in a pull request if you're willing to review/merge.

Thanks.

**Comment by ignrdmonster** [comment]
Anyway you could post it or fork this into a maintained version? This was justifying me not buying some sensor to monitor this locally.

**Comment by ignrdmonster** [comment]
Looks like someone already forked this: https://github.com/thebradleysanders/evergy_home_assistant  @Ben-Reg  Just found it myself and i'm migrating over now.

**Comment by Ben-Reg** [comment]
@ignrdmonster
Sure, I'll find some time to post the fix here.

Is that evergy_home_assistant project working for you?  I took a quick look at the code and it appears to me that they would be affected by this same issue.

**Comment by ignrdmonster** [comment]
They’re affected by the exact same thing. Figured 3 emails about this issue at midnight would be too many. On May 3, 2023, at 9:57 AM, Ben-Reg ***@***.***> wrote:﻿
@ignrdmonster
Sure, I'll find some time to post the fix here.
Is that evergy_home_assistant project working for you?  I took a quick look at the code and it appears to me that they would be affected by this same issue.

**Comment by thebradleysanders** [comment]
I am working to resolve the issue in the Home Assistant Evergy Integration. @lawrencefoley will be the official source for the Evergy Python API, while I will use this within the Home Assistant Evergy Integration, keeping these separate will make maintenance easier. Thanks everyone!
